### ISSUE TITLE
Sidebar bug

### ISSUE THREAD

**Issue by JulienItard** [BookingSync/bootstrap-bookingsync-sass#52]
![capture du 2016-08-24 12 59 09](https://cloud.githubusercontent.com/assets/1370893/17929200/39b051e6-69ff-11e6-82dd-7a16442de03f.png)

This bug appears when i open/close several time setting panel on firefox 50.0a2

**Comment by ZenCocoon** [comment]
The markup changed, important to read the changelog, specially on major version bump
