### ISSUE TITLE
Add bsy-dialog service

### ISSUE THREAD

**Issue by JovicaSusa** [BookingSync/bootstrap-bookingsync-sass#95]
Service for more styled, responsive, customizable JavaScript popup boxes.
Needed for more styled confirm dialogs and alerts.
Service extends SweetAlert2 library.

**Comment by herzzanu** [comment]
Addressed in #81

**Comment by herzzanu** [comment]
@JovicaSusa do you have any idea why the alert looks now like this? 

![image](https://user-images.githubusercontent.com/2959519/35263894-e586a5a8-001a-11e8-9163-9ec86c2baa96.png)

Can you please have a look and see how it shows for you?

**Comment by JovicaSusa** [comment]
@herzzanu Hmm, don't hava an idea, going to check.
